<?php

namespace AppBundle\Repository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * cree una nueva caracteristica
 * arregle un bug
 */
class OfertaRepository extends EntityRepository
{
    public function findOfertaDelDia($ciudad){
        $em = $this->getDoctrine()->getManager();
        $consulta = $em->createQuery('SELECT o FROM Appbundle:Oferta o WHERE 0.ciudad = :ciudad AND fechaPublicacion = :fecha ');
        $consulta->setParameters(array(
            'ciudad' => $ciudad,
            'fecha' => '2018-09-25 00:00:00'
        ))
        $consulta->setMaxResults(20);
        $cosnuilta->setFirstResult(10);
        $ofertas = $consulta->getResult();
    }
}
