# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    enabled_generator_loggin: true

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.message_generator:
         class: AppBundle\Service\MessageGenerator
         arguments: ['@logger', '%enabled_generator_loggin%']
