<?php

namespace SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UpgradeStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesUpgradeStatusRepository extends EntityRepository
{
    public function getPending()
    {
        
    }
}
