<?php

return array (
  'hash' => '09493381846fcf2c2af038f3487852395bbbbd07e1aa8',
  'translations' => 
  array (
    'messages' => 
    array (
      'brand.name.page' => 
      array (
        'files' => 
        array (
        ),
        'hash' => 'ae65588e966d7061c801a49ab7df91d15bbbbcf67420b',
        'new' => false,
        'autogenerated' => false,
        'active' => true,
        'values' => 
        array (
          'en' => 'COUPON',
          'es' => 'CUPON',
        ),
      ),
    ),
  ),
);
